name: API Governance POC

on: [push]

jobs:
  check-api:
    runs-on: ubuntu-latest
    # Kita pakai 'container' supaya tidak perlu INSTALL manual yang bikin error tadi
    container:
      image: ibmcom/apic-toolkit:latest 

    steps:
      - name: Ambil Kode dari Git
        uses: actions/checkout@v3

      - name: Jalankan Validasi Governance
        run: |
          # Perintah ini akan langsung memanggil 'Polisi' APIC
          apic governance:validate --server <URL_SERVER_ANDA> --api jsonplaceholder.yaml --ruleset <NAMA_RULESET>
