name: API Governance POC

on: [push]

jobs:
  governance-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode dari Git
        uses: actions/checkout@v3

      - name: Install Linter Ringan (Spectral)
        run: npm install -g @stoplight/spectral-cli

      - name: Jalankan Scan Keamanan API
        run: |
          # Ini akan mengecek file API Anda secara otomatis
          # Jika ada error standar, GitHub akan langsung MERAH (Stop Build)
          spectral lint jsonplaceholder.yaml
